

export const COUNTER_INCREMENT = "COUNTER_INCREMENT"

export const COUNTER_DECREMENT = "COUNTER_DECREMENT"

export const GET_MEDISIN = "GET_MEDISIN"

export const POST_MEDISIN = "POST_MEDISIN"
export const DELETE_MEDISIN = "DELETE_MEDISIN"
export const UPDATE_MEDESIN ="UPDATE_MEDESIN"
export const LODING_MEDESIN = "LODING_MEDESIN"
export const ERROR_MEDESIN = "ERROR_MEDESIN"